@startuml Figma
skinparam class {
BackgroundColor PaleGreen
ArrowColor SeaGreen
BorderColor Black
}

header <b>TCP</b>

class "Machine-1" as M1 {
    - {static} String owner (Boris)
    + {static} String network (Internet)
    - Boolean isConnected 
}
note right of M1 : Client 

class "Machine-2" as M2 {
   - {static} String owner (SF)
   + {static} String network (Internet)
   - Boolean isConnected 
}
note right of M2 : Serveur 


class "Network" as N #LightGrey{
    {field} String Protocol (TCP)
    - Boolean isCongested 
}

JSON "Protocol" as P1 #LightSalmon {
    "name":"TCP",
    "ar": "ACK",
    "oriented":"connection"
}

json "User" as U1 #LightSalmon {
    "firstname": "Boris",
    "lastname": "R"
}

note as UN
   <b><color:royalBlue>tcp.adoc</color>
end note

P1 -[#LightSalmon,dotted,thickness=2]-> N #text:gray : plays a part in
U1 -[#LightSalmon,dotted,thickness=2]-> M1 #text:gray : belongs to
M2 .. UN 
UN .. M1
M2 -up-> N #text:gray : Browsing the Web
N <-down- M1 #text:gray : File transfer



@enduml