name: Dev Workflow
run-name: ${{ github.actor }} Dev Worflow
on:
  push:
    branches:
      - dev
  workflow_call:
    inputs:
      username:
        description: 'My github name passed from the caller workflow'
        default: 'boris-rose'
        required: false
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Debugging Information
        run: |
          echo "Workflow triggered by: ${{ github.actor }}"
          echo "Event name: ${{ github.event_name }}"
          echo "Username: ${{ inputs.username }}"
      
      - name: Testing if my name is shown
        run: echo "dev workflow initiated by ${{ inputs.username }}"