name: dev-workflow
on:
    push:
        branches:
            - dev
    workflow_call:
        inputs:
            username:
                description: 'My github name passed from the caller workflow'
                default: 'boris-rose'
                required: false
                type: string

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Testing if my name is shown
              run: echo dev worflow initiated by ${{ inputs.username }}