name: dev-worflow
run-name: ${{ github.actor }} dev-worflow
on:
    push:
        branches:
            - dev
    workflow_call:
        inputs:
            username:
                description: 'My github name passed from the caller workflow'
                default: 'Boris-Rose'
                required: false
                type: string

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Testing if my name is showns
              run: echo dev worflow initiated by ${{ inputs.username }}