name: dev-worflow
run-name: ${{ github.actor }} dev-worflow
on:
    push:
        branches:
            dev
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - run: echo "test"