name: Notes Push 
run-name: ${{ github.actor }} / Notes Push
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            node: [14, 16]    
    # defaults:
    #     run:
    #       working-directory: ./scripts
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/checkout@v4
      - run: ./init.sh
      - run: ./scripts/test.sh
