name: test-workflow
run-name: ${{ github.actor}} test-workflow
on:
    push:
        branches:
            - dev
jobs:
    test-job-one:
        runs-on: ubuntu-latest
        steps:
        - name: test-step-one
          uses: ./.github/worflows/helper
        - name: test-step-two
          run: echo 'test done'
